services:
  faster_whisper:
    image: quay.io/ktbs/fd-itbs-dms/faster_whisper:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faster_whisper
    ports:
      - '50001:50001'
    environment:
      - http_proxy
      - HTTP_PROXY
      - https_proxy
      - HTTPS_PROXY
      - no_proxy
      - NO_PROXY
    volumes:
      - hugging_face_cache:/root/.cache/huggingface

volumes:
  hugging_face_cache: