services:
  faster_whisper:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
      - "quay.io/ktbs/fd-itbs-dms/faster-whisper:latest"
      - "quay.io/ktbs/fd-itbs-dms/faster-whisper:1.0.0"
    ports:
      - '9001:50001'
    environment:
      - http_proxy
      - HTTP_PROXY
      - https_proxy
      - HTTPS_PROXY
      - no_proxy
      - NO_PROXY
      - TIMEOUT
      - MAX_CONCURRENCY
      - MAX_BATCH_SIZE
      - MAX_LATENCY_MS
    volumes:
      - hugging_face_cache:/root/.cache/huggingface
    networks:
      - default
      - monitoring-network 
    deploy:
      resources:
        reservations:
          memory: 16g
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Expose Prometheus UI
    networks:
      - default
      - monitoring-network 
  
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana_data:/var/lib/grafana  # Persist Grafana data
    ports:
      - "3000:3000"  # Expose Grafana UI
    depends_on:
      - prometheus
    networks:
          - default
          - monitoring-network

volumes:
  hugging_face_cache:

networks:
  monitoring-network: